alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_AUTOMAKER foreign key (AUTOMAKER_ID) references CARDEALER_AUTOMAKER(ID);
create index IDX_CARDEALER_CAR_ON_AUTOMAKER on CARDEALER_CAR (AUTOMAKER_ID);
