alter table CARDEALER_CAR_MODEL add constraint FK_CARDEALER_CAR_MODEL_ON_AUTOMAKER foreign key (AUTOMAKER_ID) references CARDEALER_AUTOMAKER(ID);
create index IDX_CARDEALER_CAR_MODEL_ON_AUTOMAKER on CARDEALER_CAR_MODEL (AUTOMAKER_ID);
