alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_AUTOMAKER foreign key (AUTOMAKER_ID) references CARDEALER_AUTOMAKER(ID);
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references CARDEALER_CAR_MODEL(ID);
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references CARDEALER_EQUIPMENT(ID);
create index IDX_CARDEALER_CAR_ON_AUTOMAKER on CARDEALER_CAR (AUTOMAKER_ID);
create index IDX_CARDEALER_CAR_ON_CAR_MODEL on CARDEALER_CAR (CAR_MODEL_ID);
create index IDX_CARDEALER_CAR_ON_EQUIPMENT on CARDEALER_CAR (EQUIPMENT_ID);
