alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references CARDEALER_CAR_MODEL(ID);
create index IDX_CARDEALER_CAR_ON_CAR_MODEL on CARDEALER_CAR (CAR_MODEL_ID);
