alter table CARDEALER_AUTOMAKER add constraint FK_CARDEALER_AUTOMAKER_ON_COUNTRY foreign key (COUNTRY_ID) references CARDEALER_COUNTRY(ID);
create unique index IDX_CARDEALER_AUTOMAKER_UNIQ_CODE on CARDEALER_AUTOMAKER (CODE) ;
create unique index IDX_CARDEALER_AUTOMAKER_UNIQ_NAME on CARDEALER_AUTOMAKER (NAME) ;
create index IDX_CARDEALER_AUTOMAKER_ON_COUNTRY on CARDEALER_AUTOMAKER (COUNTRY_ID);
